const clients=[
{name:'Mariana Costa',stage:'Documentação',score:68,status:'attention',last:3,pending:'Comprovante complementar',next:'Confirmar recebimento do documento'},
{name:'Carlos Mendes',stage:'Documentação',score:42,status:'high',last:11,pending:'Documento pendente há 11 dias',next:'Confirmar dificuldade no envio'},
{name:'Fernanda Lima',stage:'Análise',score:47,status:'high',last:15,pending:'Sem interação há 15 dias',next:'Realizar contato de acompanhamento'},
{name:'Pedro Alves',stage:'Diagnóstico',score:73,status:'attention',last:2,pending:'Nova solicitação documental',next:'Orientar sobre documento solicitado'},
{name:'Ana Ribeiro',stage:'Análise',score:76,status:'attention',last:8,pending:'Etapa sem atualização há 8 dias',next:'Verificar andamento e atualizar status'},
{name:'Luiza Rocha',stage:'Preparação',score:91,status:'healthy',last:1,pending:'Nenhuma',next:'Orientar etapa final'},
{name:'Rafael Souza',stage:'Pós-atendimento',score:95,status:'healthy',last:0,pending:'Nenhuma',next:'Coletar NPS'}];
const stages=['Necessidade','Atendimento','Diagnóstico','Documentação','Análise','Pendências','Preparação','Contratação','Pós'];
let view='dashboard'; const app=document.querySelector('#app');
function badge(c){return `<span class="badge ${c.status}">${c.status==='healthy'?'Saudável':c.status==='attention'?'Atenção':'Acompanhamento'}</span>`}
function layout(content){app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">Jornada360</div><div class="tag">CX • Customer Success</div><nav class="nav">${[['dashboard','Visão geral'],['clients','Clientes'],['priorities','Prioridades'],['cx','Voz do Cliente'],['customer','Visão do cliente']].map(([v,l])=>`<button data-v="${v}" class="${view===v?'active':''}">${l}</button>`).join('')}</nav></aside><main class="main">${content}</main></div>`;document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()})}
function dashboard(){layout(`<div class="top"><div><h1>Visão geral da carteira</h1><p class="sub">Quem precisa de atenção e quais atritos estão afetando a jornada?</p></div><span class="pill">Ambiente demonstrativo • dados fictícios</span></div><section class="grid4">${[['38','Clientes ativos'],['22','Jornadas saudáveis'],['11','Em atenção'],['5','Necessitam acompanhamento']].map(x=>`<div class="card metric"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</section><section class="cols"><div class="card"><h2>Prioridades de hoje</h2>${clients.filter(c=>c.status!=='healthy').slice(0,4).map(c=>`<div class="row"><div><b>${c.name}</b><div class="small">${c.stage}</div></div><div>${c.pending}<div class="small">Próxima ação: ${c.next}</div></div><div>${badge(c)}</div></div>`).join('')}</div><div class="card"><h2>Insight CX</h2><p>Documentação é o principal ponto de atrito desta carteira demonstrativa.</p><p class="small">Ação sugerida: revisar orientações e acompanhar pendências antigas. A sugestão apoia o profissional; não toma decisões financeiras.</p></div></section>`)}
function clientList(){layout(`<div class="top"><div><h1>Carteira de clientes</h1><p class="sub">Acompanhamento organizado por jornada e necessidade de ação.</p></div></div><div class="toolbar"><input id="q" placeholder="Buscar cliente"><select id="filter"><option value="all">Todos</option><option value="high">Acompanhamento</option><option value="attention">Atenção</option><option value="healthy">Saudável</option></select></div><div class="card" id="list"></div>`);const draw=()=>{let q=document.querySelector('#q').value.toLowerCase(),f=document.querySelector('#filter').value;document.querySelector('#list').innerHTML=clients.filter(c=>c.name.toLowerCase().includes(q)&&(f==='all'||c.status===f)).map((c,i)=>`<div class="row"><div><b>${c.name}</b><div class="small">${c.stage}</div></div><div>Health ${c.score}/100<div class="small">${c.pending}</div></div><div>${badge(c)} <button class="btn" data-client="${clients.indexOf(c)}">Abrir</button></div></div>`).join('');document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>detail(+b.dataset.client))};document.querySelector('#q').oninput=draw;document.querySelector('#filter').onchange=draw;draw()}
function detail(i){const c=clients[i];view='clients';layout(`<div class="top"><div><h1>Cliente 360º — ${c.name}</h1><p class="sub">Visão da experiência e do acompanhamento. Não é análise de crédito.</p></div>${badge(c)}</div><div class="grid4"><div class="card metric"><strong>${c.score}/100</strong><span>Saúde da jornada</span></div><div class="card metric"><strong>${c.stage}</strong><span>Etapa atual</span></div><div class="card metric"><strong>${c.last} dias</strong><span>Desde a última interação</span></div><div class="card metric"><strong>${c.pending==='Nenhuma'?'0':'1'}</strong><span>Pendências ativas</span></div></div><div class="card" style="margin-top:18px"><h2>Jornada</h2><div class="journey">${stages.map((s,n)=>`<div class="stage ${n<3?'done':s.startsWith(c.stage.slice(0,5))?'current':''}">${s}</div>`).join('')}</div></div><section class="cols"><div class="card"><h2>Pendência / acompanhamento</h2><p>${c.pending}</p><p><b>Próxima ação:</b> ${c.next}</p><button class="btn alt" onclick="alert('Interação fictícia registrada para demonstração.')">Registrar interação</button></div><div class="card"><h2>Por que este score?</h2><div class="score">${c.score}</div><div class="reason">Evolução da jornada</div><div class="reason">Situação documental</div><div class="reason">Pendências e tempo sem atualização</div><p class="small">Renda, idade, gênero, endereço e outros atributos pessoais não entram no cálculo.</p></div></section>`)}
function priorities(){layout(`<div class="top"><div><h1>Central de Prioridades</h1><p class="sub">Motivo da sinalização + próxima ação, sem associação a risco de crédito.</p></div></div><div class="grid4">${[['5','Acompanhamento'],['11','Em atenção'],['7','Pendências documentais'],['4','Sem interação']].map(x=>`<div class="card metric"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</div><div class="card" style="margin-top:18px"><h2>Quem precisa de acompanhamento hoje</h2>${clients.filter(c=>c.status!=='healthy').map(c=>`<div class="row"><div><b>${c.name}</b><div class="small">${c.stage}</div></div><div>${c.pending}<div class="small">Próxima ação: ${c.next}</div></div><div>${badge(c)}</div></div>`).join('')}</div><p class="notice">Prioridade indica necessidade de acompanhamento da experiência. Não representa risco de crédito, elegibilidade ou probabilidade de aprovação.</p>`)}
function cx(){layout(`<div class="top"><div><h1>Voz do Cliente</h1><p class="sub">Feedback transformado em aprendizado sobre a jornada.</p></div></div><div class="grid4"><div class="card metric"><strong>4,3/5</strong><span>CSAT demonstrativo</span></div><div class="card metric"><strong>+42</strong><span>NPS demonstrativo</span></div><div class="card metric"><strong>76%</strong><span>Conclusão</span></div><div class="card metric"><strong>24%</strong><span>Interrupção</span></div></div><section class="cols"><div class="card"><h2>Atritos mais citados</h2><div class="reason">Documentação — 41%</div><div class="reason">Tempo de espera — 28%</div><div class="reason">Comunicação/status — 19%</div><div class="reason">Outros — 12%</div></div><div class="card"><h2>Comentários fictícios</h2><p>“Gostei de saber exatamente o que faltava.”</p><p>“Queria receber atualização mesmo quando ainda estivesse aguardando.”</p><p class="small">A IA futura poderá classificar temas e resumir feedback, mas não decidirá questões financeiras.</p></div></section>`)}
function customer(){layout(`<div class="top"><div><h1>Experiência mobile do cliente</h1><p class="sub">A tela deve responder: onde estou, preciso fazer algo e qual é o próximo passo?</p></div></div><div class="mobile-wrap"><div class="phone"><div class="small">Jornada360</div><h2>Olá, Mariana</h2><p class="small">Sua jornada está em andamento.</p><div class="progress"><i></i></div><p><b>Etapa atual:</b> Documentação</p><div class="action-box"><b>Você precisa fazer algo agora?</b><h3>Sim</h3><p>Envie o comprovante complementar solicitado.</p><button class="btn">Ver orientação</button></div><div class="card"><b>Próximo passo</b><p>Após a conferência, sua jornada poderá seguir para a etapa de análise.</p><span class="small">Última atualização: há 3 dias</span></div><h3>Como foi sua experiência até aqui?</h3><div class="survey">${[1,2,3,4,5].map(n=>`<button onclick="this.style.background='#efe8f0'">${n}</button>`).join('')}</div><p class="notice">Demonstração de portfólio. O acompanhamento exibido não representa aprovação ou decisão de instituição financeira.</p></div></div>`)}
function render(){({dashboard,clients:clientList,priorities,cx,customer}[view]||dashboard)()}render();
